### ISSUE TITLE
Need help on include the js/css which are present in inner folders not on root.

### ISSUE THREAD

**Issue by appasosawant** [imranbaloch/ASP.NET-Optimization-Framework-and-Embeded-Resource#1]
I have tried your application. It is working good, but i have problem when including the js or css wich are present in my dll are in hierarchical i.e. in inner folders not on root. How to includes this file in AppStart function. Please help. Thank you.

**Comment by imranbaloch** [comment]
Actually I don't understand. The source code is open. You can put the necessary classes in your project and debug.

**Comment by appasosawant** [comment]
suppose u have js in subfoldre in SampleHelper. So at the time of including that js what things we need to do. You have code to include js like this:
BundleTable.Bundles.Add(new ScriptBundle("~/ImranB/Embedded/Js")
                        .Include("~/ImranB/Embedded/NewTextBox1.js")

Now suppose we have one folder under root say JSFiles. Now I want that file in this folder to be included as embeded resource. Where i need to change in AppStart.
Do i need to add like  .Include("~/ImranB/Embedded/JSFiles/NewTextBox1.js")?

**Comment by appasosawant** [comment]
The code which you have is helpful to include the js and css which are present on root in in folder. Please advice on this. Thank you.

**Comment by imranbaloch** [comment]
Embedded resource have nothing to do with sub-folders(AFAIK). Your resources are just embeded in the dll. You can check the embedded resource in dll using some dis-assembler tools(iLSpy or JustDecompile)

**Comment by appasosawant** [comment]
But as per your code, we need virtual path to point the embeded resources present in bundle in dll from MVC app.So my question is, at the time of configuring the bundle what paths are what configure i need to do to include the files present in folder. I have moved the NewTextBox1.js from root to new subfolder with name JSFiles. Then application throws the error. then i tried like : .Include("~/ImranB/Embedded/JSFiles/NewTextBox1.js")
But this is also not working. Basically i want the embeded resource to be used from sub folders insteade of root. Thank you for you help.

**Comment by appasosawant** [comment]
But as per your code, we need virtual path to point the embeded resources present in bundle in dll from MVC app.So my question is, at the time of configuring the bundle what paths need to use to include the files present in folder. I have moved the NewTextBox1.js from root to new subfolder with name JSFiles. Then application throws the error. then i tried like : .Include("~/ImranB/Embedded/JSFiles/NewTextBox1.js")
But this is also not working. Basically i want the embeded resource to be used from sub folders insteade of root. Thank you for you help.

**Comment by imranbaloch** [comment]
Oh Got it. you need to use folder name in the path,
.Include("~/ImranB/Embedded/JSFiles.aaa.js")

**Comment by appasosawant** [comment]
Ok, got it. Thanks a lot for your kind help and time.
