### ISSUE TITLE
Start in WebActivator.PostApplicationStartMethod is not workin on IIS 6. Is ther any alternate method available

### ISSUE THREAD

**Issue by appasosawant** [imranbaloch/ASP.NET-Optimization-Framework-and-Embeded-Resource#2]
I have working application on local machine. But when i deployed it on SERVER which is having IIS6.0. It is not working. Is there any configuration i need to add?

**Comment by imranbaloch** [comment]
Please ask this question at https://github.com/davidebbo/WebActivator

**Comment by appasosawant** [comment]
Thank you
