### ISSUE TITLE
JS and CSS files are not found when loaded from server.

### ISSUE THREAD

**Issue by appasosawant** [imranbaloch/ASP.NET-Optimization-Framework-and-Embeded-Resource#3]
Following is code is working fine without error (I have checked with try and catch) FROM AppStart:

BundleTable.VirtualPathProvider = new EmbeddedVirtualPathProvider(HostingEnvironment.VirtualPathProvider);

```
            //bundle for common js
            BundleTable.Bundles.Add(new ScriptBundle("~/XXXXXXX/Embedded/Js")
            .Include("~/XXXXXXX/Embedded/Scripts.jquery-1.10.2.js")
            .Include("~/XXXXXXX/Embedded/Scripts.jquery-ui.min.js")
            .Include("~/XXXXXXX/Embedded/Scripts.YYYY.js")
            .Include("~/XXXXXXX/Embedded/Scripts.YYYYY.js")
            .Include("~/XXXXXXX/Embedded/Scripts.YYYYYY.js")
            );
```

BundleTable.Bundles.Add(new StyleBundle("~/XXXXXXX/Embedded/SelectCss")
                .Include("~/XXXXXXX/Embedded/Style.XX.css")

AND 

public static MvcHtmlString RenderSelect(this HtmlHelper html)
        {

```
        var js = Scripts.Render("~/XXXXXXX/Embedded/Js").ToString();
        var css = Styles.Render("~/XXXXXXX/Embedded/SelectCss").ToString();
        return MvcHtmlString.Create(js  + css );
    }
```

When It is rendered on browser we are able to see Scripts.jquery-1.10.2.js, Scripts.jquery-ui.min.js, etc. But content of this files are like 

<h1>The page cannot be found</h1>

The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.

<hr>

<p>Please try the following:</p>

<ul>
<li>Make sure that the Web site address displayed in the address bar of your browser is spelled and formatted correctly.</li>
<li>If you reached this page by clicking a link, contact
 the Web site administrator to alert them that the link is incorrectly formatted.
</li>
</ul>

<h2>HTTP Error 404 - File or directory not found.<br></h2>

<hr>

With HTML syntax’s.

**Comment by appasosawant** [comment]
I have checked with david, webactivator is working fine and the method PostApplicationStartMethod is working too.

**Comment by appasosawant** [comment]
please find the screenshot of js files.js files are loaded with some message, css and not loaded.

**Comment by imranbaloch** [comment]
Make sure debug=false

**Comment by appasosawant** [comment]
<compilation debug="false" targetFramework="4.0" batch="true">
no luck.

**Comment by appasosawant** [comment]
do i need to add EmbeddedResourceHttpHandler entry in my MVC application web.config?

**Comment by imranbaloch** [comment]
I don't think. If you are in Azure you can also remote debug
